<?php

/**
 * @file
 * Contains module file.
 */

/**
 * Implements hook_theme().
 */
function twig_storybook_theme($themes) {
  $themes = [
    'page__storybook' => [
      'variables' => ['variables' => NULL],
    ],
    'storybook_template' => [
      'variables' => ['variables' => NULL],
    ],
  ];

  return $themes;
}

/**
 * Implements hook_page_attachments().
 */
function twig_storybook_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'twig_storybook/global-styling';
}
